export const SHOW_DETAIL = "SHOW_DETAIL";
export const DELETE_ITEM = "DELETE_ITEM";
export const QUALITY_PHONE_ITEM_INCREA = "QUALITY_PHONE_ITEM_INCREA";
export const QUALITY_PHONE_ITEM_DECREA = "QUALITY_PHONE_ITEM_DECREA";
export const ADD_SHOPPING_CARD = "ADD_SHOPPING_CARD";
